# Generated by Django 6.1 on 2026-09-03 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profilevideoreaction_profilevideoview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videomoderationevent',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='videomoderationevent',
            index=models.Index(fields=['new_status', 'archived_at', '-created_at'], name='profiles_vi_new_sta_71a89a_idx'),
        ),
    ]
