# Generated by Django 6.1 on 2026-09-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_videomoderationevent_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfileConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='profiles.professionalprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['profile', '-created_at'], name='profiles_pr_profile_4c90f2_idx')],
            },
        ),
    ]
