# Generated by Django 6.1 on 2026-09-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_videomoderationevent_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'ordering': ('-updated_at', 'pk'), 'permissions': (('manage_skill_catalog', 'Peut gerer le referentiel de competences'), ('view_private_profile', 'Peut consulter un profil prive'), ('moderate_profile', 'Peut moderer un profil'))},
        ),
    ]
