# Generated by Django 6.1 on 2026-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_professionalprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
