# Generated by Django 6.1 on 2026-09-01 12:50

import django.db.models.deletion
import profils.questionnaires.models.questionnaire
import profils.questionnaires.question_types
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('max_level', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(default=profils.questionnaires.models.questionnaire.new_stable_key, editable=False, max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='', help_text="affichee dans les resultats si la visibilite l'autorise")),
                ('type', models.CharField(choices=profils.questionnaires.question_types.type_choices, max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('expected_config', models.JSONField(blank=True, default=dict)),
                ('scoring_config', models.JSONField(blank=True, default=dict)),
                ('condition', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('TEST', 'Test'), ('PUBLISHED', 'Publie'), ('DISABLED', 'Desactive'), ('ARCHIVED', 'Archive'), ('INVALIDATED', 'Invalide')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='None = tentatives illimitees', null=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text="duree maximale d'une tentative une fois commencee", null=True)),
                ('attempt_expiry_seconds', models.PositiveIntegerField(blank=True, help_text='delai au-dela duquel une tentative inachevee expire', null=True)),
                ('allow_retry_after_pass', models.BooleanField(default=False)),
                ('allow_retry_after_fail', models.BooleanField(default=True)),
                ('keep_previous_attempts', models.BooleanField(default=True)),
                ('answer_edit_mode', models.CharField(choices=[('FREE', 'Modifiables librement'), ('UNTIL_FINISH', "Modifiables jusqu'a la fin de la tentative"), ('LOCKED_ON_VALIDATE', 'Verrouillees des validation')], default='UNTIL_FINISH', max_length=20)),
                ('navigation_mode', models.CharField(choices=[('FREE', 'Navigation libre'), ('LINEAR', 'Lineaire')], default='FREE', max_length=10)),
                ('allow_back', models.BooleanField(default=True)),
                ('result_visibility', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'permissions': (('publish_questionnaire', 'Peut publier un questionnaire'), ('archive_questionnaire', 'Peut archiver un questionnaire'), ('invalidate_questionnaire', 'Peut invalider un questionnaire'), ('test_questionnaire', 'Peut tester un questionnaire'), ('manage_versions', 'Peut gerer les versions'), ('manage_access', "Peut gerer les regles d'acces"), ('view_attempts', 'Peut consulter les tentatives'), ('view_results', 'Peut consulter les resultats'), ('view_statistics', 'Peut consulter les statistiques'), ('manage_badges', 'Peut gerer les badges')),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('ABANDONED', 'Abandonnee'), ('EXPIRED', 'Expiree'), ('INVALIDATED', 'Invalidee')], default='IN_PROGRESS', max_length=12)),
                ('is_test', models.BooleanField(default=False, help_text='tentative de mode TEST : exclue des statistiques et des badges reels')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('visible_count', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionnaires.question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questionnaires.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('TEST', 'Test'), ('PUBLISHED', 'Publie'), ('DISABLED', 'Desactive'), ('ARCHIVED', 'Archive'), ('INVALIDATED', 'Invalide')], default='DRAFT', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scoring_config', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questionnaire_versions', to=settings.AUTH_USER_MODEL)),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='questionnaires.questionnaireversion')),
                ('invalidated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalidated_questionnaire_versions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_questionnaire_versions', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ('questionnaire', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passed', models.BooleanField()),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('is_test', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='questionnaires.questionnaireattempt')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='questionnaires.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_results', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='questionnaires.questionnaireversion')),
            ],
            options={
                'ordering': ('-computed_at',),
            },
        ),
        migrations.AddField(
            model_name='questionnaireattempt',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='questionnaires.questionnaireversion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionnaires.questionnaireversion'),
        ),
        migrations.AddField(
            model_name='question',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaireversion'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(default=profils.questionnaires.models.questionnaire.new_stable_key, editable=False, max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('value', models.CharField(blank=True, default='', help_text="valeur portee par l'option (echelle, notation...)", max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=3, help_text='score specifique a cette option (optionnel)', max_digits=8, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_stable_key', models.CharField(db_index=True, max_length=32)),
                ('value', models.JSONField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('score_details', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('client_sequence', models.BigIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.questionnaireattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaires.question')),
            ],
            options={
                'ordering': ('question__order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserAnswerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_stable_key', models.CharField(db_index=True, max_length=32)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='questionnaires.useranswer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='questionnaires.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('QUESTIONNAIRE_RESULT', 'Resultat de questionnaire'), ('MANUAL', 'Attribution manuelle'), ('SYSTEM', 'Systeme')], default='SYSTEM', max_length=24)),
                ('is_test', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='questionnaires.badge')),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to='questionnaires.questionnaireresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-awarded_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('PUBLISH', 'PUBLISH'), ('INVALIDATE', 'INVALIDATE'), ('ARCHIVE', 'ARCHIVE'), ('DISABLE', 'DISABLE'), ('RESTORE', 'RESTORE'), ('DUPLICATE', 'DUPLICATE'), ('VERSION_CREATE', 'VERSION_CREATE'), ('ACCESS_CHANGE', 'ACCESS_CHANGE'), ('QUESTION_CHANGE', 'QUESTION_CHANGE'), ('OPTION_CHANGE', 'OPTION_CHANGE'), ('SCORING_CHANGE', 'SCORING_CHANGE'), ('TEST_MODE', 'TEST_MODE'), ('BADGE_AWARD', 'BADGE_AWARD')], max_length=24)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=40)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['questionnaire', '-created_at'], name='questionnai_questio_cd5660_idx'), models.Index(fields=['object_type', 'object_id'], name='questionnai_object__cba0fd_idx'), models.Index(fields=['action'], name='questionnai_action_aeeffb_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACCESS', 'Accessibilite'), ('VISIBILITY', 'Visibilite')], default='ACCESS', max_length=12)),
                ('group_index', models.PositiveIntegerField(default=0)),
                ('rule_type', models.CharField(choices=[('EVERYONE', 'Tout le monde'), ('USER', 'Utilisateur'), ('ROLE', 'Role'), ('BADGE', 'Badge')], max_length=12)),
                ('negate', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='questionnaires.badge')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='questionnaires.questionnaire')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'group_index', 'id'),
                'indexes': [models.Index(fields=['questionnaire', 'kind', 'group_index'], name='questionnai_questio_d8f3a4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='questionnaireversion',
            index=models.Index(fields=['status'], name='questionnai_status_b301f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireversion',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'version_number'), name='unique_version_number_per_questionnaire'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresult',
            index=models.Index(fields=['user', 'questionnaire'], name='questionnai_user_id_5e8ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresult',
            index=models.Index(fields=['questionnaire', 'is_test'], name='questionnai_questio_5b4d02_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresult',
            index=models.Index(fields=['version'], name='questionnai_version_eb54dc_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireattempt',
            index=models.Index(fields=['user', 'questionnaire', 'status'], name='questionnai_user_id_9603be_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireattempt',
            index=models.Index(fields=['questionnaire', 'is_test', 'status'], name='questionnai_questio_18d98c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireattempt',
            index=models.Index(fields=['version', 'status'], name='questionnai_version_e2aed9_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnaireattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('user', 'questionnaire', 'is_test'), name='one_attempt_in_progress_per_user_questionnaire'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['status'], name='questionnai_status_36a9dd_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['available_from', 'available_until'], name='questionnai_availab_4be8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['stable_key'], name='questionnai_stable__153093_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('version', 'stable_key'), name='unique_question_key_per_version'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'stable_key'), name='unique_option_key_per_question'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question'], name='questionnai_attempt_aabf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question_stable_key'], name='questionnai_questio_5da66d_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['idempotency_key'], name='questionnai_idempot_8529f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='one_answer_per_question_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='useranswerselection',
            index=models.Index(fields=['option'], name='questionnai_option__1d9812_idx'),
        ),
        migrations.AddConstraint(
            model_name='useranswerselection',
            constraint=models.UniqueConstraint(fields=('answer', 'option'), name='unique_selection_per_answer'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'badge'], name='questionnai_user_id_f6258d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='unique_badge_per_user'),
        ),
    ]
