# Generated by Django 6.1 on 2026-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_questionnaire_carry_over_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('PUBLISH', 'PUBLISH'), ('INVALIDATE', 'INVALIDATE'), ('ARCHIVE', 'ARCHIVE'), ('DISABLE', 'DISABLE'), ('RESTORE', 'RESTORE'), ('DUPLICATE', 'DUPLICATE'), ('VERSION_CREATE', 'VERSION_CREATE'), ('ACCESS_CHANGE', 'ACCESS_CHANGE'), ('QUESTION_CHANGE', 'QUESTION_CHANGE'), ('OPTION_CHANGE', 'OPTION_CHANGE'), ('SCORING_CHANGE', 'SCORING_CHANGE'), ('TEST_MODE', 'TEST_MODE'), ('BADGE_AWARD', 'BADGE_AWARD'), ('BADGE_REVOKE', 'BADGE_REVOKE'), ('RESCORE', 'RESCORE')], max_length=24),
        ),
    ]
