#!/usr/bin/env bash

set -euo pipefail

NAME='profilsactifs'

if [ "$1" = "install" ]; then
    sudo apt-get update
    sudo apt-get remove -y docker docker-engine docker.io containerd runc 
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    echo "Installation complete"
    exit 0
elif [ "$1" = "shell" ]; then
    sudo docker exec -it $NAME sh
    exit 0
elif [ "$1" = "run" ]; then
    export PORT="${2:-8080}"
    echo "Lancement sur le port $PORT"
    sudo PORT="$PORT" docker compose watch
    exit 0
elif [ "$1" = "stop" ]; then
    sudo docker kill $NAME
    exit 0
elif [ "$1" = "logs" ]; then
    sudo docker logs -f $NAME
    exit 0
else
    echo "Usage: $0 <argument>

    arguments:
    - install: install all the packages
    - run: start the project [port (8080 by default)]
    - stop: stop the project
    - shell: run shell of the project
    - logs: print docker's logs
    "
    exit 1 
fi