#!/usr/bin/env bash

set -euo pipefail

NAME='profilsactifs'

if [ "$1" = "install" ]; then
    apt-get update
    apt-get remove -y docker docker-engine docker.io containerd runc 
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    echo "Installation complete"
    exit 0
elif [ "$1" = "shell" ]; then
    docker exec -it $NAME sh
    exit 0
elif [ "$1" = "run" ]; then
    PORT="${2:-8080}"
    echo "Lancement sur le port $PORT"
    touch db.sqlite3
    PORT="$PORT" docker compose up --watch --build
    docker compose down
    exit 0
elif [ "$1" = "start" ]; then
    PORT="${2:-8080}"
    echo "Lancement sur le port $PORT"
    touch db.sqlite3
    PORT="$PORT" docker compose up --watch --build
    exit 0
elif [ "$1" = "stop" ]; then
    docker kill $NAME
    exit 0
elif [ "$1" = "logs" ]; then
    docker logs -f $NAME
    exit 0
else
    echo "Usage: $0 <argument>

    arguments:
    - install: install all the packages
    - run: start the project [port (8080 by default)] and kill it
    - start: start the project [port (8080 by default)]
    - stop: stop the project
    - shell: run shell of the project
    - logs: print docker's logs
    "
    exit 1 
fi