#!/usr/bin/env bash

set -euo pipefail

if [ "$1" = "install" ]; then
    sudo apt-get update
    sudo apt-get remove -y docker docker-engine docker.io containerd runc 
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    echo "Installation complete"
    exit 1
elif [ "$1" = "shell" ]; then
    docker exec -it profilsactifs sh
    exit 1
elif [ "$1" = "run" ]; then
    export PORT="${2:-8080}"
    echo "Lancement sur le port $PORT"
    docker compose watch
    exit 1
elif [ "$1" = "stop" ]; then
    docker kill profilsactifs
    exit 1
else
    echo "Usage: $0 <argument>

    arguments:
    - install: install all the packages
    - run: start the project [port (8080 by default)]
    - stop: stop the project
    - shell: run shell of the project
    "
    exit 1 
fi