# Generated by Django 6.1 on 2026-09-03 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='file',
            field=models.FileField(default=None, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
            preserve_default=False,
        ),
    ]
