# Generated by Django 6.1 on 2026-09-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_role_birth_date'),
        ('mainapp', '0010_videofile_file'),
    ]

    operations = [
    ]
