# Generated by Django 6.1 on 2026-09-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_0010_role_birth_date_0010_videofile_file'),
        ('mainapp', '0011_videolink_rejection_reason_videolink_status'),
    ]

    operations = [
    ]
