# Generated by Django 6.1 on 2026-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_merge_20260903_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
