# Generated by Django 6.1 on 2026-09-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_videofile_rejection_reason_videofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
