

ROLES = ("Recruiter", "JobSeeker", "Admin")
REACTIONS = ("like", "dislike")

VIDEOFILE_STORAGE_PATH = "videos/"
MINIMUM_REGISTRATION_AGE = 18

VIDEO_LINK_PENDING  = "PENDING"
VIDEO_LINK_APPROVED = "APPROVED"
VIDEO_LINK_REJECTED = "REJECTED"

VIDEO_LINK_STATUSES = (VIDEO_LINK_PENDING, VIDEO_LINK_APPROVED, VIDEO_LINK_REJECTED)
