name: Build and Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t profils-app:latest .

      - name: Exporter l'image en fichier tar
        run: docker save profils-app:latest -o profils-app.tar

      - name: Publier l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: profils-app-docker
          path: profils-app.tar